# Generated by Django 6.0.2 on 2026-02-07 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('job_role', models.CharField(max_length=150)),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('industry', models.CharField(max_length=150)),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alumni_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('PLACED', 'Placed'), ('NOT_PLACED', 'Not Placed')], max_length=20)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='alumni.alumniprofile')),
            ],
        ),
    ]
